baseurl = "https://sougetsu-prog.github.io/pages/"
languageCode = "ja-jp"
title = "Notatki Sougetsu"
theme = "blackburn"
author = "Sougetsu"
copyright = "&copy; 2021. All rights reserved."
canonifyurls = true
publishDir = "docs"
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  # subtitle = "A Hugo Theme"
  brand = "Menu"
  # googleAnalytics = "Your Google Analytics tracking ID"
  disqus = "notatka-sougetsu"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  # dateFormat = "02 Jan 2006, 15:04"
  dateFormat = "2006/01/02"
  google_fonts = "https://fonts.googleapis.com/css2?family=Inconsolata&family=Lato:wght@400;700&family=Libre+Baskerville"
  custom_css = ["css/my.css"]

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/about/"
  # [[menu.main]]
  #   name = "Contact"
  #   pre = "<i class='fa fa-phone fa-fw'></i>"
  #   weight = 4
  #   url = "/contact/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  # twitter="*"
  # gnusocial="*"
  # facebook="*"
  # weibo="*"
  # tumblr="*"
  # instagram="*"
  # flickr="*"
  # photo500px="*"
  # pinterest="*"
  # youtube="*"
  # vimeo="*"
  # vine="*"
  # slideshare="*"
  # linkedin="*"
  # xing="*"
  # reddit="*"
  # hackernews="*"
  github="Sougetsu-Prog"
  # gitlab="*"
  # bitbucket="*"
  # stackoverflow="*"
  # serverfault="*"
  # steam="*"
  # mobygames="*"
  # lastfm="*"
  # discogs="*"
  # keybase="*"
[language]
  hasCJKLanguage = true

[time]
  timeZone = "Asia/Tokyo"
